### ISSUE TITLE
Provide packages for Fedora

### ISSUE THREAD

**Issue by lig** [rwos/gti#24]
- [ ] Put in COPR
- [ ] Push to main Fedora repo

**Comment by rwos** [comment]
@lig sorry, bit late - but `gti` is already in Fedora: https://admin.fedoraproject.org/pkgdb/package/rpms/gti/

I should probably add that to the README...

**Comment by lig** [comment]
Great! Thanks!

On Fri, Mar 18, 2016 at 4:49 PM Richard Wossal <notifications@github.com>
wrote:

> @lig <https://github.com/lig> sorry, bit late - but gti is already in
> Fedora: https://admin.fedoraproject.org/pkgdb/package/rpms/gti/
>
> I should probably add that to the README...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/rwos/gti/issues/24#issuecomment-198369073>
>
-- 
Serge Matveenko
mailto: serge@matveenko.ru
github: https://github.com/lig/
aboutme: https://about.me/lig1
