### ISSUE TITLE
OS X iTerm 2

### ISSUE THREAD

**Issue by srepollock** [rwos/gti#25]
Love the GTI, only problem is on OS X with iTerm2 and oh-my-zsh installed the car runs over the current path being displayed, and clears it. I don't know if this is a feature or a bug, but just gets a little annoying because I can't see where lines end/begin again

**Comment by rwos** [comment]
hmhmhm, I thought that was fixed? I'll check.

**Comment by rwos** [comment]
So, we used to overwrite the prompt (https://github.com/rwos/gti/pull/18) but current master looks good for me (bash with simplistic prompt, but should be the same for zsh with fancy prompt):

![prompt](https://cloud.githubusercontent.com/assets/747372/14426857/cca4fc40-fff1-11e5-9ec2-cd9098f9647d.png)

@srepollock maybe you're not using the latest and greatest version?

**Comment by rwos** [comment]
oi, I didn't tag that fix - have done so now - v1.3.0 should solve all your problems*

*maybe
