### ISSUE TITLE
Animation really slow and sluggish

### ISSUE THREAD

**Issue by JuhaniGeniem** [rwos/gti#28]
The animation goes fine the first third. The last two thirds take atleast 10 seconds.

Used the command "gti" without anything else.

Using it on:

macOS Sierra
Version 10.12

MacBook Pro (Retina, 15-inch, Mid 2015)
Processor 2,2 GHz Intel Core i7
Memory 16 GB 1600 MHz DDR3
Graphics Intel Iris Pro 1536 MB

iTerm2

zsh

**Comment by rwos** [comment]
Does that happen in all terminal emulators? Maybe something weird with iTerm2? There is nothing CPU intensive going on here, a 20Mhz 386 should be more than enough to render the animation.

**Comment by rwos** [comment]
I asked a colleague with pretty much the same setup - macOS Sierra and ITerm2 - and it works for him. So not sure what's going on there, sorry.

**Comment by JuhaniGeniem** [comment]
I'm leaning towards oh-my-zsh shell extension. It seems to work with fish.
