### ISSUE TITLE
Make gti ignore signals

### ISSUE THREAD

**Issue by BenBE** [rwos/gti#36]
Hey, I just wanted to say everything works fantastically.

Not sure why I even opened this issue. Maybe it's just a hinch.

I'm using `gti` on
* [ ] HP-UX running on a 68k
* [ ] NetBSD, with output piped to a slice of toast
* [ ] an unreleased beta version of Windows NT 4.0 with a cmd.exe replacement from ReactOS
* [X] a hobby to build some free operating system for 386 AT clones that won't be big and professional like GNU

and it
* [ ] set fire to my line printer
* [ ] hard-linked `/bin/emacs` to`/bin/vi`
* [ ] crashes when run backwards in my home-grown CPU emulator
* [X] hardly resembled it's decendents like Minix

One particular difference is the sl command, which ignores interrupts to allow for additional user education. Optionally it might be possible to disable this behaviour turning the right command line nobs.

**Comment by rwos** [comment]
I know that `sl` does that but I personally *hate* that. 😄  So, sorry, but `gti` will remain friendlier than `sl`.
