### ISSUE TITLE
That's not a GTI

### ISSUE THREAD

**Issue by pmg103** [rwos/gti#37]
I'd say more like a Lada Niva.

![image](https://user-images.githubusercontent.com/12135652/30064287-2e657456-9249-11e7-9cee-5d7763d9dd80.png)

**Comment by pmg103** [comment]
Maybe I just have my terminal font too tall

**Comment by rwos** [comment]
Well, better ASCII art is always welcome, but it's supposed to be a Mark-1 Golf GTI. You can always alias `gti` to `niva` though.

**Comment by andys8** [comment]
Comparison

![Screenshot_20191012-234002](https://user-images.githubusercontent.com/13085980/66708064-3213cf80-ed4b-11e9-983f-479519649751.png)


![Screenshot_20191012-234022](https://user-images.githubusercontent.com/13085980/66708066-393add80-ed4b-11e9-87a0-54d590fc12e7.png)

![My-Gif-Mirror-Effect-mirroreffect-com-785617263~2](https://user-images.githubusercontent.com/13085980/66708081-6dae9980-ed4b-11e9-8d75-c2df4f794082.jpg)
[](url)
