### ISSUE TITLE
Installation on Windows-based Bash?

### ISSUE THREAD

**Issue by KevinTyrrell** [rwos/gti#38]
I'm using Git Bash on Windows. I have access to basic bash commands and things like my bash_profile. How would I install this? Essentially `gti` is just an alias to run code from the C file, right?

**Comment by rwos** [comment]
@KevinTyrrell Well, you'd obviously have to build if first, but I have no idea where you would put it on Windows, sorry. Depending on how close the thing emulates a Unix system, just doing `make` followed by `make install` might even work.

`gti` just calls `git` (or whatever is in your `GIT` environment variable), but it will complain if it can't find it.

**Comment by KevinTyrrell** [comment]
Yeah unfortunately not, as seen here: https://i.imgur.com/3JUdBBK.png

How would I setup an alias that points to the C file somehow? For example, I type the alias `gti` and then it calls a bash script which then runs a function inside the C file.

**Comment by coladict** [comment]
On Windows you don't put binaries in one big common path to make them globally accessible, like you do on Linux with `/usr/bin` or `/usr/local/bin`. Instead you install your binaries wherever you wish, preferably in this case would be `%PROGRAMFILES%\gti`, then add that to the global `PATH` variable. How that's done in a script would very much depend if it's run through a MingW-Bash console or a regular console.

**Comment by KevinTyrrell** [comment]
@coladict I understand what you mean. Hmm.... is there a way then to easily translate the code in the C file to being a bash script? I'm extremely familiar with C but not nearly as familiar with bash.

**Comment by rwos** [comment]
Well, you'll still have to build/compile it, so you'll either need Visual Studio, or cygwin or something that ships with a C compiler. There's also a [node port](https://github.com/dunckr/GTI) but for that you'd obviously need node.

And last but not least, you *can* rewrite it in bash, but you'd have to do that by hand.
