### ISSUE TITLE
Add bionic package to PPA

### ISSUE THREAD

**Issue by mpsijm** [rwos/gti#40]
Would be nice :slightly_smiling_face:

Workaround for people encountering this issue:
- Edit `/etc/apt/sources.list.d/mamantoha-ubuntu-gti-bionic.list` as root
- Change `bionic` to `artful`
- Save
- Optionally, rename the file as well
- `apt update`
- `apt install gti`
- `gti pull`

**Comment by rwos** [comment]
Sorry, but I can't do that since it's not actually my PPA (https://github.com/rwos/gti/pull/39). The only thing I have control over is the source. Though I guess I should see if I can put a debian/ubuntu package somewhere, seems like the last major distro that doesn't have it.

**Comment by mamantoha** [comment]
Fixed

**Comment by rwos** [comment]
@mamantoha Magic! :smile: Thank you!
