### ISSUE TITLE
aliases

### ISSUE THREAD

**Issue by jota191** [rwos/gti#47]
My usual typo is "gir", not gti. Also steam locomotive adds some aliases such as "LS".

I propose to add two aliases: "gir" and "GIT"

This can be done in the Makefile, installing a couple of links. If you think it is ok I can work on it and add a PR.

**Comment by SuperSandro2000** [comment]
or you add the following to your rc file:

```shell
alias gir=gti
alias GIT=gti
```

**Comment by jota191** [comment]
Yep, I know (I use one: 'gpom', guess for what :) ).
Still, I think this could be given ootb.

**Comment by rwos** [comment]
But the joke with the GTI only works with `gti`. Adding sub commands is fine, but I don't think I want to add more aliases, this program is annoying enough as is :)
