### ISSUE TITLE
OSI-approved license?

### ISSUE THREAD

**Issue by chenrui333** [rwos/gti#48]
I have a trouble to map the license of the repo, I wonder if we can use simpler licenses that is in https://spdx.org/licenses

**Comment by rwos** [comment]
It's just the MIT license, in what's sometimes called "old style" - https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#Old_Style

Same license as XScreensaver for example: https://github.com/Zygo/xscreensaver/blob/d1f484cfa47f4a0862140421480bb536ad66ede9/hacks/analogtv.h#L3-L9

**Comment by chenrui333** [comment]
oh cool. Thanks for clarifying it.
