### ISSUE TITLE
Ubuntu PPA has been deleted.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [rwos/gti#51]
Hey, I just wanted to say that the Ubuntu PPA seems to have been deleted. I can’t find any related public opened PPA´s by mamantoha https://launchpad.net/~mamantoha/+ppa-packages

Not sure why I even opened this issue, instead of pull requesting a change in the README.md

Oh, yeah because I wasn’t sure if it was known or not.

**Comment by rwos** [comment]
Ha, thanks for letting me know! I'll remove that for now, and will think about offering packages myself in the future, probably better than random PPAs.

**Comment by rwos** [comment]
Link removed in https://github.com/rwos/gti/commit/6dcde1e8426512198cdd01058d5bdd2381cbc775, thanks again!
