### ISSUE TITLE
Can you also include LICENSE file in the source code

### ISSUE THREAD

**Issue by chenrui333** [rwos/gti#61]
While adding the license for [the formula update](https://github.com/Homebrew/homebrew-core/pull/99966), I realized that the license file did not get included in the source code, can you include the LICENSE file in the source code so that when the artifact got used in somewhere the license can be cross-referenced. Thanks!

**Comment by rwos** [comment]
The license was in gti.c and README.md, but I have added a LICENSE file now, too.

**Comment by chenrui333** [comment]
Thanks @rwos!
